const listings = [
    { image: "House Images/DefaultHouse.jpg", price: 1000000, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false },
    { image: "House Images/listing2.jpg", price: 500000, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false },
    { image: "House Images/listing3.jpg", price: 325000, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false },
    { image: "House Images/listing4.jpg", price: 5000000, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false },
    { image: "House Images/listing5.jpg", price: 175000, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false },
    { image: "House Images/listing6.png", price: 895000, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false },
    { image: "House Images/listing7.jpg", price: 2500000, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false },
    { image: "House Images/listing8.jpg", price: 450000, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false },
    { image: "House Images/listing9.jpg", price: 670000, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false },
    { image: "House Images/listing10.jpg", price: 5, description: "Welcome to this delightful 3-bedroom, 2-bathroom residence situated in the heart of a serene and family-friendly neighborhood. This home boasts a perfect blend of modern comfort and classic charm, making it an ideal place for both newcomers and those looking to upgrade their living experience.", location: "Location: 1942 Cape Cod, Carthage Missouri, USA", isListed: false }];

function getRandomListing(ran) {
    return listings[ran];
}

function setListed(ran) {
    listings[ran].isListed = true;
}